export default {
	0: { icon: 'cloud' },

	200: { icon: 'poo-storm' },
	201: { icon: 'poo-storm' },
	202: { icon: 'poo-storm' },
	210: { icon: 'poo-storm' },
	211: { icon: 'poo-storm' },
	212: { icon: 'poo-storm' },
	221: { icon: 'poo-storm' },
	230: { icon: 'poo-storm' },
	231: { icon: 'poo-storm' },
	232: { icon: 'poo-storm' },

	300: { icon: 'cloud-showers-heavy' },
	301: { icon: 'cloud-showers-heavy' },
	302: { icon: 'cloud-showers-heavy' },
	310: { icon: 'cloud-showers-heavy' },
	311: { icon: 'cloud-showers-heavy' },
	312: { icon: 'cloud-showers-heavy' },
	313: { icon: 'cloud-showers-heavy' },
	314: { icon: 'cloud-showers-heavy' },
	321: { icon: 'cloud-showers-heavy' },

	500: { icon: 'cloud-sun-rain' },
	501: { icon: 'cloud-sun-rain' },
	502: { icon: 'cloud-sun-rain' },
	503: { icon: 'cloud-sun-rain' },
	504: { icon: 'cloud-sun-rain' },
	511: { icon: 'cloud-meatball' },
	520: { icon: 'cloud-rain' },
	521: { icon: 'cloud-rain' },
	522: { icon: 'cloud-rain' },
	531: { icon: 'cloud-rain' },

	600: { icon: 'cloud-meatball' },
	601: { icon: 'cloud-meatball' },
	602: { icon: 'cloud-meatball' },
	611: { icon: 'cloud-meatball' },
	612: { icon: 'cloud-meatball' },
	613: { icon: 'cloud-meatball' },
	615: { icon: 'cloud-meatball' },
	616: { icon: 'cloud-meatball' },
	620: { icon: 'cloud-meatball' },
	621: { icon: 'cloud-meatball' },
	622: { icon: 'cloud-meatball' },

	701: { icon: 'smog' },
	711: { icon: 'smog' },
	721: { icon: 'smog' },
	731: { icon: 'smog' },
	741: { icon: 'smog' },
	751: { icon: 'smog' },
	761: { icon: 'smog' },
	762: { icon: 'smog' },
	771: { icon: 'smog' },
	781: { icon: 'smog' },

	800: { icon: 'sun' },

	801: { icon: 'cloud-sun' },
	802: { icon: 'cloud' },
	803: { icon: 'cloud' },
	804: { icon: 'cloud' },
};
