var weathericons = {
	"200": "fas fa-poo-storm",
	"201": "fas fa-poo-storm",
	"202": "fas fa-poo-storm",
	"210": "fas fa-poo-storm",
	"211": "fas fa-poo-storm",
	"212": "fas fa-poo-storm",
	"221": "fas fa-poo-storm",
	"230": "fas fa-poo-storm",
	"231": "fas fa-poo-storm",
	"232": "fas fa-poo-storm",

	"300": "fas fa-cloud-showers-heavy",
	"301": "fas fa-cloud-showers-heavy",
	"302": "fas fa-cloud-showers-heavy",
	"310": "fas fa-cloud-showers-heavy",
	"311": "fas fa-cloud-showers-heavy",
	"312": "fas fa-cloud-showers-heavy",
	"313": "fas fa-cloud-showers-heavy",
	"314": "fas fa-cloud-showers-heavy",
	"321": "fas fa-cloud-showers-heavy",

	"500": "fas fa-cloud-sun-rain",
	"501": "fas fa-cloud-sun-rain",
	"502": "fas fa-cloud-sun-rain",
	"503": "fas fa-cloud-sun-rain",
	"504": "fas fa-cloud-sun-rain",
	"511": "fas fa-cloud-meatball",
	"520": "fas fa-cloud-rain",
	"521": "fas fa-cloud-rain",
	"522": "fas fa-cloud-rain",
	"531": "fas fa-cloud-rain",

	"600": "fas fa-cloud-meatball",
	"601": "fas fa-cloud-meatball",
	"602": "fas fa-cloud-meatball",
	"611": "fas fa-cloud-meatball",
	"612": "fas fa-cloud-meatball",
	"613": "fas fa-cloud-meatball",
	"615": "fas fa-cloud-meatball",
	"616": "fas fa-cloud-meatball",
	"620": "fas fa-cloud-meatball",
	"621": "fas fa-cloud-meatball",
	"622": "fas fa-cloud-meatball",

	"701": "fas fa-smog",
	"711": "fas fa-smog",
	"721": "fas fa-smog",
	"731": "fas fa-smog",
	"741": "fas fa-smog",
	"751": "fas fa-smog",
	"761": "fas fa-smog",
	"762": "fas fa-smog",
	"771": "fas fa-smog",
	"781": "fas fa-smog",

	"800": "fas fa-sun",

	"801": "fas fa-cloud-sun",
	"802": "fas fa-cloud",
	"803": "fas fa-cloud",
	"804": "fas fa-cloud"
};